Cource3#HW1 Finish
J0ker001/school_Cource3_HW1 pull request #1
Opened 2022-04-28 20:33 UTC by J0ker001

2022-04-29 23:02 UTC, OKrylov requested changes
В целом по работе все сделано практически верно, но стоит учесть замечания, которые я оствавил.

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public List<Map.Entry<Long, Faculty>> filteredColor(@PathVariable String color) {
нам нужна коллекция факультетов, мапу не нужно возвращать

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public List<Map.Entry<Long, Student>> filteredColor(@PathVariable Integer age) {
аналогично, нужен только список, не мапа

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        faculty.setId(lastID++);
лучше начинать с 1 значения, тогда надо использовать префиксную запись
```suggestion
        faculty.setId(++lastID);
```

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        --lastID;
айди не нужно уменьшать, удалили, будут пробелы с индексом, что есть норма

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +    public List<Map.Entry<Long, Faculty>> sortFaculties(String color) {
нам нужна коллекция факультетов, а не пары значений из мепы

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +public class StudentService {
не забываем создавать интерфейсы для сервисов

2022-04-29 23:02 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +    public List<Map.Entry<Long, Student>> sortStudent(Integer age) {
аналогичное замечание

2022-05-01 22:24 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public List<Map.Entry<Long, Faculty>> filteredColor(@PathVariable String color) {
+

2022-05-01 22:24 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public List<Map.Entry<Long, Student>> filteredColor(@PathVariable Integer age) {
+

2022-05-01 22:24 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        faculty.setId(lastID++);
+

2022-05-01 22:25 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        --lastID;
+

2022-05-01 22:25 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +    public List<Map.Entry<Long, Faculty>> sortFaculties(String color) {
+

2022-05-01 22:26 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +    public List<Map.Entry<Long, Student>> sortStudent(Integer age) {
+

2022-05-01 22:51 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +public class StudentService {
+.
 В лекции было сказано, что не обязательно. На практике, как понял у всех все индивидуально  ?

2022-05-03 21:27 UTC, OKrylov approved these changes
По исправлениям все верно, оставил только одно минорное замечание

2022-05-03 21:27 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> -    private final StudentService studentService;
тут как раз меня не нужно было, мы должны использовать интерфейсы вместо явной реализации

2022-05-04 16:02 UTC, merged