Cource3#HW3 Finish
J0ker001/school_Cource3_HW1 pull request #3
Opened 2022-05-07 07:30 UTC by J0ker001

2022-05-08 12:14 UTC, OKrylov requested changes
В целом работа выполнена практически идеально, но есть несколько замечаний, большую чвсть которых мы уже обсуждали на разборе ДЗ, просьба обратить на них внимание

2022-05-08 12:14 UTC, OKrylov commented on scripts.sql
> +select name
стоит визуально разделить запросы, в идеале оставить перед каждым комментарий, что он означает

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public Collection<Faculty> findByNameOrColor(@RequestParam(required = false) @PathVariable String name,
стоит использовать только один из типов параметров, либо Path, либо Request. Можно присвоить параметрам запроса оригинальные имена, чтобы обойти совпадения с другими методами

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    @GetMapping("between/{minAge},{maxAge}")
лучше использовать @RequestParam

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public List<Student> filteredStudent(@PathVariable Integer age) {
лучше использовать @RequestParam

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public Collection<Student> findByName(@PathVariable String name) {
лучше использовать @RequestParam

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public Student findByFaculty_Id(@PathVariable("name") String name) {
```suggestion
    public Student findByFacultyId(@PathVariable("name") String name) {
```

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    @GetMapping("facult/{name}")
лучше использовать @RequestParam

2022-05-08 12:14 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/repositories/FacultyRepository.java
> +    List<Faculty> findByNameOrColorAllIgnoreCase(String name, String color);
есть подозрение что IngoreCase распорстраняется только на Color

2022-05-10 17:13 UTC, J0ker001 commented on scripts.sql
> +select name
+

2022-05-10 17:24 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public List<Student> filteredStudent(@PathVariable Integer age) {
+

2022-05-10 17:35 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public Collection<Student> findByName(@PathVariable String name) {
+

2022-05-10 17:37 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    public Student findByFaculty_Id(@PathVariable("name") String name) {
+

2022-05-10 17:40 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/repositories/FacultyRepository.java
> +    List<Faculty> findByNameOrColorAllIgnoreCase(String name, String color);
работает

2022-05-10 17:42 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    @GetMapping("facult/{name}")
+

2022-05-10 17:52 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/StudentController.java
> +    @GetMapping("between/{minAge},{maxAge}")
+

2022-05-10 18:01 UTC, J0ker001 commented on src/main/java/ru/hogwarts/school/controllers/FacultyController.java
> +    public Collection<Faculty> findByNameOrColor(@RequestParam(required = false) @PathVariable String name,
+

2022-05-10 18:04 UTC, merged